// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerShell.MinistryPlatform.v001.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Provides basic metadata about a stored procedure.
    /// </summary>
    public partial class ProcedureInfo
    {
        /// <summary>
        /// Initializes a new instance of the ProcedureInfo class.
        /// </summary>
        public ProcedureInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProcedureInfo class.
        /// </summary>
        /// <param name="name">Gets or sets the routine name.</param>
        /// <param name="parameters">Gets collection of routine
        /// parameters.</param>
        public ProcedureInfo(string name = default(string), IList<ParameterInfo> parameters = default(IList<ParameterInfo>))
        {
            Name = name;
            Parameters = parameters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the routine name.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets collection of routine parameters.
        /// </summary>
        [JsonProperty(PropertyName = "Parameters")]
        public IList<ParameterInfo> Parameters { get; set; }

    }
}
