// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerShell.MinistryPlatform.v001
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Communications.
    /// </summary>
    public static partial class CommunicationsExtensions
    {
            /// <summary>
            /// Returns communication corresponding to the provided identifier.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='communicationId'>
            /// Identifier of the communication to be returned.
            /// </param>
            public static Communication Get(this ICommunications operations, int communicationId)
            {
                return operations.GetAsync(communicationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns communication corresponding to the provided identifier.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='communicationId'>
            /// Identifier of the communication to be returned.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Communication> GetAsync(this ICommunications operations, int communicationId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(communicationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes communication corresponding to the provided identifier.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='communicationId'>
            /// Identifier of the communication to be deleted.
            /// </param>
            public static object Delete(this ICommunications operations, int communicationId)
            {
                return operations.DeleteAsync(communicationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes communication corresponding to the provided identifier.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='communicationId'>
            /// Identifier of the communication to be deleted.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> DeleteAsync(this ICommunications operations, int communicationId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteWithHttpMessagesAsync(communicationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Creates new communication, immediately renders it and schedules for
            /// delivery.
            /// </summary>
            /// <remarks>
            /// This Action supports both single-part and multi-part form data. If
            /// multi-part form
            /// is submitted, it must include a section with serialized
            /// {Platform.Web.Services.PowerService.CommunicationInfo} object.
            /// Other sections may include file attachments. The sample JSON and XML
            /// requests are below:
            ///
            ///
            /// Authorization: Bearer &amp;lt;binary access token&amp;gt;
            /// Accept: application/json
            /// Content-Type: multipart/form-data;
            /// boundary=---------------------------7df359143903c8
            ///
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-0"; filename="file1.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 1
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-1"; filename="file2.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 2
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="communication"
            /// Content-Type: application/json
            ///
            /// {
            /// AuthorUserId: 4,
            /// Subject: "Test Subject",
            /// Body: "Test Body",
            /// FromContactId: 2,
            /// ReplyToContactId: 2,
            /// Contacts: [200145,200109,200536]
            /// }
            ///
            /// Authorization: Bearer &amp;lt;binary access token&amp;gt;
            /// Accept: application/xml
            /// Content-Type: multipart/form-data;
            /// boundary=---------------------------7df359143903c8
            ///
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-0"; filename="file1.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 1
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-1"; filename="file2.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 2
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="communication"
            /// Content-Type: application/xml
            ///
            /// &amp;lt;CommunicationInfo
            /// xmlns="http://www.thinkministry.com/dataplatform/2012/10/"&amp;gt;
            /// &amp;lt;AuthorUserId&amp;gt;4&amp;lt;/AuthorUserId&amp;gt;
            /// &amp;lt;Body&amp;gt;Test Body&amp;lt;/Body&amp;gt;
            /// &amp;lt;Contacts&amp;gt;
            /// &amp;lt;int&amp;gt;200145&amp;lt;/int&amp;gt;
            /// &amp;lt;int&amp;gt;200109&amp;lt;/int&amp;gt;
            /// &amp;lt;int&amp;gt;200536&amp;lt;/int&amp;gt;
            /// &amp;lt;/Contacts&amp;gt;
            /// &amp;lt;FromContactId&amp;gt;2&amp;lt;/FromContactId&amp;gt;
            /// &amp;lt;ReplyToContactId&amp;gt;2&amp;lt;/ReplyToContactId&amp;gt;
            /// &amp;lt;Subject&amp;gt;Test Subject&amp;lt;/Subject&amp;gt;
            /// &amp;lt;StartDate&amp;gt;2017-01-01T00:00:00&amp;lt;/StartDate&amp;gt;
            /// &amp;lt;/CommunicationInfo&amp;gt;
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static Communication PostAsync(this ICommunications operations)
            {
                return operations.PostAsyncAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates new communication, immediately renders it and schedules for
            /// delivery.
            /// </summary>
            /// <remarks>
            /// This Action supports both single-part and multi-part form data. If
            /// multi-part form
            /// is submitted, it must include a section with serialized
            /// {Platform.Web.Services.PowerService.CommunicationInfo} object.
            /// Other sections may include file attachments. The sample JSON and XML
            /// requests are below:
            ///
            ///
            /// Authorization: Bearer &amp;lt;binary access token&amp;gt;
            /// Accept: application/json
            /// Content-Type: multipart/form-data;
            /// boundary=---------------------------7df359143903c8
            ///
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-0"; filename="file1.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 1
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-1"; filename="file2.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 2
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="communication"
            /// Content-Type: application/json
            ///
            /// {
            /// AuthorUserId: 4,
            /// Subject: "Test Subject",
            /// Body: "Test Body",
            /// FromContactId: 2,
            /// ReplyToContactId: 2,
            /// Contacts: [200145,200109,200536]
            /// }
            ///
            /// Authorization: Bearer &amp;lt;binary access token&amp;gt;
            /// Accept: application/xml
            /// Content-Type: multipart/form-data;
            /// boundary=---------------------------7df359143903c8
            ///
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-0"; filename="file1.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 1
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="file-1"; filename="file2.txt"
            /// Content-Type: application/octet-stream
            ///
            /// file 2
            /// -----------------------------7df359143903c8
            /// Content-Disposition: form-data; name="communication"
            /// Content-Type: application/xml
            ///
            /// &amp;lt;CommunicationInfo
            /// xmlns="http://www.thinkministry.com/dataplatform/2012/10/"&amp;gt;
            /// &amp;lt;AuthorUserId&amp;gt;4&amp;lt;/AuthorUserId&amp;gt;
            /// &amp;lt;Body&amp;gt;Test Body&amp;lt;/Body&amp;gt;
            /// &amp;lt;Contacts&amp;gt;
            /// &amp;lt;int&amp;gt;200145&amp;lt;/int&amp;gt;
            /// &amp;lt;int&amp;gt;200109&amp;lt;/int&amp;gt;
            /// &amp;lt;int&amp;gt;200536&amp;lt;/int&amp;gt;
            /// &amp;lt;/Contacts&amp;gt;
            /// &amp;lt;FromContactId&amp;gt;2&amp;lt;/FromContactId&amp;gt;
            /// &amp;lt;ReplyToContactId&amp;gt;2&amp;lt;/ReplyToContactId&amp;gt;
            /// &amp;lt;Subject&amp;gt;Test Subject&amp;lt;/Subject&amp;gt;
            /// &amp;lt;StartDate&amp;gt;2017-01-01T00:00:00&amp;lt;/StartDate&amp;gt;
            /// &amp;lt;/CommunicationInfo&amp;gt;
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Communication> PostAsyncAsync(this ICommunications operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostAsyncWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
