// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerShell.MinistryPlatform.v001
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// Provides RESTful programming interface to data managed by Think
    /// Ministry Data Platform.
    /// </summary>
    public partial interface IPlatformAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the ICommunications.
        /// </summary>
        ICommunications Communications { get; }

        /// <summary>
        /// Gets the IFiles.
        /// </summary>
        IFiles Files { get; }

        /// <summary>
        /// Gets the IMessages.
        /// </summary>
        IMessages Messages { get; }

        /// <summary>
        /// Gets the IProcedures.
        /// </summary>
        IProcedures Procedures { get; }

        /// <summary>
        /// Gets the ITables.
        /// </summary>
        ITables Tables { get; }

        /// <summary>
        /// Gets the ITasks.
        /// </summary>
        ITasks Tasks { get; }

        /// <summary>
        /// Gets the IUsers.
        /// </summary>
        IUsers Users { get; }

    }
}
